//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string hotel_name { get; set; }
        public int id_cities { get; set; }
        public string img_src { get; set; }
        public Nullable<int> rank { get; set; }
    }
}
