//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string hotel_name { get; set; }
        public int id_cities { get; set; }
        public string img_src { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> price { get; set; }
        public string about { get; set; }
    }
}
